use sanjusto;

CREATE TABLE SJ_CUSTOMERS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CUSTOMER_NAME VARCHAR(200) NOT NULL,
    ADDRESS VARCHAR(500) NOT NULL,
    PHONE VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(100),
    START_DATE DATE NOT NULL,
    ENABLED INT NOT NULL DEFAULT 1);

CREATE TABLE SJ_USERS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME VARCHAR(30) NOT NULL,
    MIDDLE_NAME VARCHAR(30),
    LAST_NAME VARCHAR(30) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    USERNAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(1000),
    ENABLED INT NOT NULL DEFAULT 1,
    CONSTRAINT UK_USERS_USERNAME UNIQUE(USERNAME),
    CONSTRAINT UK_USERS_EMAIL UNIQUE(EMAIL));
    