use crm;

CREATE TABLE ORGANIZATIONS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    ENABLED INT NOT NULL DEFAULT 1,
    CONSTRAINT UK_ORG_NAME UNIQUE (NAME));

CREATE TABLE TYPES (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TYPE VARCHAR(20) NOT NULL,
    SHORT_NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(2000) NOT NULL,
    ENABLED INT NOT NULL DEFAULT 1,
    PARENT_TYPE INT DEFAULT NULL,
    ORG_ID INT NOT NULL,
    CONSTRAINT UK_TYPE_NAME_TYPES UNIQUE(TYPE,SHORT_NAME),
    CONSTRAINT FK_TYPES_ORG FOREIGN KEY (ORG_ID) REFERENCES ORGANIZATIONS (ID),
    CONSTRAINT FK_TYPES_TYPES FOREIGN KEY (PARENT_TYPE) REFERENCES TYPES (ID));

CREATE TABLE CUSTOMERS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CUSTOMER_NAME VARCHAR(200) NOT NULL,
    ADDRESS VARCHAR(500) NOT NULL,
    NEIGHBORHOOD VARCHAR(100) NOT NULL,
    CITY VARCHAR(100) NOT NULL,
    PHONE VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(100),
    START_DATE DATETIME NOT NULL,
    CUSTOMER_TYPE INT NOT NULL,
    ENABLED INT NOT NULL DEFAULT 1,
    ORG_ID INT NOT NULL,
    CONSTRAINT FK_CT_TYPES FOREIGN KEY (CUSTOMER_TYPE) REFERENCES TYPES (ID),
    CONSTRAINT FK_CUSTOMERS_ORG FOREIGN KEY (ORG_ID) REFERENCES ORGANIZATIONS (ID));

CREATE TABLE BRANCHES (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    BRANCH_NAME VARCHAR(200) NOT NULL,
    ADDRESS VARCHAR(500) NOT NULL,
    NEIGHBORHOOD VARCHAR(100) NOT NULL,
    CITY VARCHAR(100) NOT NULL,
    PHONE VARCHAR(20) NOT NULL,
    START_DATE DATETIME NOT NULL,
    CUSTOMER_ID INT NOT NULL,
    BRANCH_TYPE INT NOT NULL,
    ENABLED INT NOT NULL DEFAULT 1,
    ORG_ID INT NOT NULL,
    CONSTRAINT FK_BT_TYPES FOREIGN KEY (BRANCH_TYPE) REFERENCES TYPES (ID),
    CONSTRAINT FK_BRANCH_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID),
    CONSTRAINT FK_BRANCHES_ORG FOREIGN KEY (ORG_ID) REFERENCES ORGANIZATIONS (ID));

CREATE TABLE CONTACTS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME VARCHAR(50) NOT NULL,
    MIDDLE_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PHONE VARCHAR(20) NOT NULL,
    ENABLED INT NOT NULL DEFAULT 1,
    ORG_ID INT NOT NULL,
    CONSTRAINT UK_CONTACT_EMAIL UNIQUE(EMAIL),
    CONSTRAINT FK_CONTACTS_ORG FOREIGN KEY (ORG_ID) REFERENCES ORGANIZATIONS (ID));

CREATE TABLE BRANCHES_CONTACTS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CONTACT_ID INT NOT NULL,
    BRANCH_ID INT NOT NULL,
    PRIORITY INT NOT NULL DEFAULT 1,    
    ENABLED INT NOT NULL DEFAULT 1,
    CONSTRAINT UK_CONTACT_BRANCH UNIQUE (CONTACT_ID,BRANCH_ID),
    CONSTRAINT FK_BC_CONTACTS FOREIGN KEY (CONTACT_ID) REFERENCES CONTACTS (ID),
    CONSTRAINT FK_BC_BRANCHES FOREIGN KEY (BRANCH_ID) REFERENCES BRANCHES (ID));

CREATE TABLE USERS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME VARCHAR(30) NOT NULL,
    MIDDLE_NAME VARCHAR(30),
    LAST_NAME VARCHAR(30) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    USERNAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(1000),
    ENABLED INT NOT NULL DEFAULT 1,
    ORG_ID INT NOT NULL,
    CONSTRAINT UK_USERS_USERNAME UNIQUE(USERNAME),
    CONSTRAINT UK_USERS_EMAIL UNIQUE(EMAIL),
    CONSTRAINT FK_USERS_ORG FOREIGN KEY (ORG_ID) REFERENCES ORGANIZATIONS (ID));
    
CREATE TABLE TREATMENTS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TREATMENT_DATE DATETIME NOT NULL,
    BRANCH_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    COORDINATED INT NOT NULL DEFAULT 0,
    FINISHED INT NOT NULL DEFAULT 0,
    MOTIVE_TYPE INT,
    CERTIFICATE INT NOT NULL DEFAULT 0,
    COMMENTS VARCHAR(4000),
    ORG_ID INT NOT NULL,
    CONSTRAINT FK_TREATMENTS_BRANCHES FOREIGN KEY (BRANCH_ID) REFERENCES BRANCHES (ID),
    CONSTRAINT FK_TREATMENTS_USERS FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    CONSTRAINT FK_TREATMENTS_MOTIVE FOREIGN KEY (MOTIVE_TYPE) REFERENCES TYPES (ID),
    CONSTRAINT FK_TREATMENTS_ORG FOREIGN KEY (ORG_ID) REFERENCES ORGANIZATIONS (ID));

CREATE TABLE TREATMENTS_WORKS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TREATMENT_ID INT NOT NULL,
    TYPE_WORK INT NOT NULL,
    CONSTRAINT FK_TREATMENTS_WORK_TYPES FOREIGN KEY (TYPE_WORK) REFERENCES TYPES (ID),
    CONSTRAINT FK_TW_TREATMENTS FOREIGN KEY (TREATMENT_ID) REFERENCES TREATMENTS (ID),
    CONSTRAINT UK_TREATMENT_WORKS UNIQUE (TREATMENT_ID,TYPE_WORK));

CREATE TABLE TREATMENTS_WORKS_DETAILS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    WORKS_ID INT NOT NULL,
    TYPE_WD INT NOT NULL,
    CONSTRAINT FK_TWD_TYPES FOREIGN KEY (TYPE_WD) REFERENCES TYPES (ID),
    CONSTRAINT FK_TWD_WORKS FOREIGN KEY (WORKS_ID) REFERENCES TREATMENTS_WORKS (ID),
    CONSTRAINT UK_TWS UNIQUE (WORKS_ID,TYPE_WD));

CREATE TABLE PRODUCTS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(1000)  NOT NULL,
    DESCRIPTION VARCHAR(4000),
    QUANTITY FLOAT NOT NULL DEFAULT 1,
    UNIT INT NOT NULL,
    ORG_ID INT NOT NULL,
    CONSTRAINT FK_PRODUCTS_TYPES FOREIGN KEY (UNIT) REFERENCES TYPES (ID),
    CONSTRAINT FK_PRODUCTS_ORG FOREIGN KEY (ORG_ID) REFERENCES ORGANIZATIONS (ID));

CREATE TABLE TREATMENTS_PRODUCTS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TREATMENT_ID INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    QUANTITY FLOAT NOT NULL DEFAULT 1,
    CONSTRAINT FK_TP_TREATMENTS FOREIGN KEY (TREATMENT_ID) REFERENCES TREATMENTS (ID),
    CONSTRAINT FK_TP_PRODUCTS FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS (ID),
    CONSTRAINT UK_TP UNIQUE (TREATMENT_ID,PRODUCT_ID));

CREATE TABLE TREATMENT_PLAGUES (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TREATMENT_ID INT NOT NULL,
    TYPE_PLAGUE INT NOT NULL,
    CONTROLLED INT NOT NULL,
    CONSTRAINT FK_TPLAGUE_TREATMENTS FOREIGN KEY (TREATMENT_ID) REFERENCES TREATMENTS (ID),
    CONSTRAINT FK_TPLAGUE_TYPE FOREIGN KEY (TYPE_PLAGUE) REFERENCES TYPES (ID),
    CONSTRAINT FK_TPLAGUE_TYPE_CONTROL FOREIGN KEY (CONTROLLED) REFERENCES TYPES (ID),
    CONSTRAINT UK_TPLAGUE UNIQUE (TREATMENT_ID,TYPE_PLAGUE));

CREATE TABLE TREATMENT_SURVEY (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TREATMENT_ID INT NOT NULL,
    TYPE_SURVEY INT NOT NULL,
    SUBTYPE_SURVEY INT NOT NULL,
    CHECKED INT DEFAULT 0,
    CONSTRAINT FK_TSURVEY_TREATMENTS FOREIGN KEY (TREATMENT_ID) REFERENCES TREATMENTS (ID),
    CONSTRAINT FK_TSURVEY_TYPE FOREIGN KEY (TYPE_SURVEY) REFERENCES TYPES (ID),
    CONSTRAINT FK_TSURVEY_SUBTYPE FOREIGN KEY (SUBTYPE_SURVEY) REFERENCES TYPES (ID),
    CONSTRAINT UK_TSURVEY UNIQUE (TREATMENT_ID,TYPE_SURVEY,SUBTYPE_SURVEY));

CREATE TABLE ROLES_USERS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_ID INT NOT NULL,
    ROLE VARCHAR(20),
    CONSTRAINT UK_ROL_USER UNIQUE (USER_ID,ROLE),
    CONSTRAINT FK_ROL_USER_USERS FOREIGN KEY (USER_ID) REFERENCES USERS (ID));