use crm;

CREATE TABLE ORGANIZATIONS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    ENABLED INT NOT NULL DEFAULT 1,
    CONSTRAINT UK_ORG_NAME UNIQUE (NAME));

CREATE TABLE TYPES (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TYPE VARCHAR(20) NOT NULL,
    SHORT_NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(2000) NOT NULL,
    ENABLED INT NOT NULL DEFAULT 1,
    ORG_ID INT NOT NULL,
    CONSTRAINT UK_TYPE_NAME_TYPES UNIQUE(TYPE,SHORT_NAME),
    CONSTRAINT FK_TYPES_ORG FOREIGN KEY (ORG_ID) REFERENCES ORGANIZATIONS (ID));

CREATE TABLE CUSTOMERS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CUSTOMER_NAME VARCHAR(200) NOT NULL,
    ADDRESS VARCHAR(500) NOT NULL,
    NEIGHBORHOOD VARCHAR(100) NOT NULL,
    CITY VARCHAR(100) NOT NULL,
    PHONE VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(100),
    START_DATE DATE NOT NULL,
    CUSTOMER_TYPE INT NOT NULL,
    ENABLED INT NOT NULL DEFAULT 1,
    ORG_ID INT NOT NULL,
    CONSTRAINT FK_CT_TYPES FOREIGN KEY (CUSTOMER_TYPE) REFERENCES TYPES (ID),
    CONSTRAINT FK_CUSTOMERS_ORG FOREIGN KEY (ORG_ID) REFERENCES ORGANIZATIONS (ID));

CREATE TABLE BRANCHES (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    BRANCH_NAME VARCHAR(200) NOT NULL,
    ADDRESS VARCHAR(500) NOT NULL,
    NEIGHBORHOOD VARCHAR(100) NOT NULL,
    CITY VARCHAR(100) NOT NULL,
    PHONE VARCHAR(20) NOT NULL,
    START_DATE DATE NOT NULL,
    CUSTOMER_ID INT NOT NULL,
    BRANCH_TYPE INT NOT NULL,
    ENABLED INT NOT NULL DEFAULT 1,
    ORG_ID INT NOT NULL,
    CONSTRAINT FK_BT_TYPES FOREIGN KEY (BRANCH_TYPE) REFERENCES TYPES (ID),
    CONSTRAINT FK_BRANCH_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID),
    CONSTRAINT FK_BRANCHES_ORG FOREIGN KEY (ORG_ID) REFERENCES ORGANIZATIONS (ID));

CREATE TABLE CONTACTS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME VARCHAR(50) NOT NULL,
    MIDDLE_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PHONE VARCHAR(20) NOT NULL,
    ENABLED INT NOT NULL DEFAULT 1,
    ORG_ID INT NOT NULL,
    CONSTRAINT UK_CONTACT_EMAIL UNIQUE(EMAIL),
    CONSTRAINT FK_CONTACTS_ORG FOREIGN KEY (ORG_ID) REFERENCES ORGANIZATIONS (ID));

CREATE TABLE BRANCHES_CONTACTS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CONTACT_ID INT NOT NULL,
    BRANCH_ID INT NOT NULL,
    PRIORITY INT NOT NULL DEFAULT 1,    
    ENABLED INT NOT NULL DEFAULT 1,
    CONSTRAINT UK_CONTACT_BRANCH UNIQUE (CONTACT_ID,BRANCH_ID),
    CONSTRAINT FK_BC_CONTACTS FOREIGN KEY (CONTACT_ID) REFERENCES CONTACTS (ID),
    CONSTRAINT FK_BC_BRANCHES FOREIGN KEY (BRANCH_ID) REFERENCES BRANCHES (ID));

CREATE TABLE USERS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME VARCHAR(30) NOT NULL,
    MIDDLE_NAME VARCHAR(30),
    LAST_NAME VARCHAR(30) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    USERNAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(1000),
    ENABLED INT NOT NULL DEFAULT 1,
    ORG_ID INT NOT NULL,
    CONSTRAINT UK_USERS_USERNAME UNIQUE(USERNAME),
    CONSTRAINT UK_USERS_EMAIL UNIQUE(EMAIL),
    CONSTRAINT FK_USERS_ORG FOREIGN KEY (ORG_ID) REFERENCES ORGANIZATIONS (ID));
    
CREATE TABLE ROLES_USERS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_ID INT NOT NULL,
    ROLE VARCHAR(20),
    CONSTRAINT UK_ROL_USER UNIQUE (USER_ID,ROLE),
    CONSTRAINT FK_ROL_USER_USERS FOREIGN KEY (USER_ID) REFERENCES USERS (ID));