CREATE TABLE SJ_CUSTOMERS (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    CUSTOMER_NAME VARCHAR(200) NOT NULL,
    ADDRESS VARCHAR(500) NOT NULL,
    PHONE VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(100),
    START_DATE DATE NOT NULL,
    ENABLE INT NOT NULL DEFAULT 1);

insert into SJ_CUSTOMERS (CUSTOMER_NAME,ADDRESS,PHONE,EMAIL,START_DATE,ENABLE)
values ('CUSTOMER ONE','ADDRESS_ONE_TEST','PHONE_ONE_TEST','emailTest1@test.com',current_date(),1);

commit;