CREATE TABLE ORGANIZATIONS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    ENABLED INT NOT NULL DEFAULT 1,
    CONSTRAINT UK_ORG_NAME UNIQUE (NAME));

CREATE TABLE TYPES (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TYPE VARCHAR(20) NOT NULL,
    SHORT_NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(2000) NOT NULL,
    ENABLED INT NOT NULL DEFAULT 1,
    PARENT_TYPE INT,
    ORG_ID INT NOT NULL,
    CONSTRAINT UK_TYPE_NAME_TYPES UNIQUE(TYPE,SHORT_NAME),
    CONSTRAINT FK_TYPES_ORG FOREIGN KEY (ORG_ID) REFERENCES ORGANIZATIONS (ID),
    CONSTRAINT FK_TYPES_TYPES FOREIGN KEY (PARENT_TYPE) REFERENCES TYPES (ID));

CREATE TABLE CUSTOMERS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CUSTOMER_NAME VARCHAR(200) NOT NULL,
    ADDRESS VARCHAR(500) NOT NULL,
    NEIGHBORHOOD VARCHAR(100) NOT NULL,
    CITY VARCHAR(100) NOT NULL,
    PHONE VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(100),
    START_DATE DATE NOT NULL,
    CUSTOMER_TYPE INT NOT NULL,
    ENABLED INT NOT NULL DEFAULT 1,
    ORG_ID INT NOT NULL,
    CONSTRAINT FK_CT_TYPES FOREIGN KEY (CUSTOMER_TYPE) REFERENCES TYPES (ID),
    CONSTRAINT FK_CUSTOMERS_ORG FOREIGN KEY (ORG_ID) REFERENCES ORGANIZATIONS (ID));

CREATE TABLE BRANCHES (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    BRANCH_NAME VARCHAR(200) NOT NULL,
    ADDRESS VARCHAR(500) NOT NULL,
    NEIGHBORHOOD VARCHAR(100) NOT NULL,
    CITY VARCHAR(100) NOT NULL,
    PHONE VARCHAR(20) NOT NULL,
    START_DATE DATE NOT NULL,
    CUSTOMER_ID INT NOT NULL,
    BRANCH_TYPE INT NOT NULL,
    ENABLED INT NOT NULL DEFAULT 1,
    ORG_ID INT NOT NULL,
    CONSTRAINT FK_BT_TYPES FOREIGN KEY (BRANCH_TYPE) REFERENCES TYPES (ID),
    CONSTRAINT FK_BRANCH_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID),
    CONSTRAINT FK_BRANCHES_ORG FOREIGN KEY (ORG_ID) REFERENCES ORGANIZATIONS (ID));

CREATE TABLE CONTACTS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME VARCHAR(50) NOT NULL,
    MIDDLE_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PHONE VARCHAR(20) NOT NULL,
    ENABLED INT NOT NULL DEFAULT 1,
    ORG_ID INT NOT NULL,
    CONSTRAINT UK_CONTACT_EMAIL UNIQUE(EMAIL),
    CONSTRAINT FK_CONTACTS_ORG FOREIGN KEY (ORG_ID) REFERENCES ORGANIZATIONS (ID));

CREATE TABLE BRANCHES_CONTACTS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CONTACT_ID INT NOT NULL,
    BRANCH_ID INT NOT NULL,
    PRIORITY INT NOT NULL DEFAULT 1,
    ENABLED INT NOT NULL DEFAULT 1,
    CONSTRAINT UK_CONTACT_BRANCH UNIQUE (CONTACT_ID,BRANCH_ID),
    CONSTRAINT FK_BC_CONTACTS FOREIGN KEY (CONTACT_ID) REFERENCES CONTACTS (ID),
    CONSTRAINT FK_BC_BRANCHES FOREIGN KEY (BRANCH_ID) REFERENCES BRANCHES (ID));

CREATE TABLE USERS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME VARCHAR(30) NOT NULL,
    MIDDLE_NAME VARCHAR(30),
    LAST_NAME VARCHAR(30) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    USERNAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(1000),
    ENABLED INT NOT NULL DEFAULT 1,
    ORG_ID INT NOT NULL,
    CONSTRAINT UK_USERS_USERNAME UNIQUE(USERNAME),
    CONSTRAINT UK_USERS_EMAIL UNIQUE(EMAIL),
    CONSTRAINT FK_USERS_ORG FOREIGN KEY (ORG_ID) REFERENCES ORGANIZATIONS (ID));

CREATE TABLE TREATMENTS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TREATMENT_DATE DATETIME NOT NULL,
    BRANCH_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    COORDINATED INT NOT NULL DEFAULT 0,
    FINISHED INT NOT NULL DEFAULT 0,
    TYPE INT NOT NULL,
    CERTIFICADO INT NOT NULL DEFAULT 0,
    COMMENTS VARCHAR(4000),
    CONSTRAINT FK_TREATMENTS_BRANCHES FOREIGN KEY (BRANCH_ID) REFERENCES BRANCHES (ID),
    CONSTRAINT FK_TREATMENTS_USERS FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    CONSTRAINT FK_TREATMENTS_TYPES FOREIGN KEY (TYPE) REFERENCES TYPES (ID));

CREATE TABLE TREATMENTS_WORKS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TREATMENT_ID INT NOT NULL,
    TYPE_WORK INT NOT NULL,
    CONSTRAINT FK_TREATMENTS_WORK_TYPES FOREIGN KEY (TYPE_WORK) REFERENCES TYPES (ID),
    CONSTRAINT FK_TW_TREATMENTS FOREIGN KEY (TREATMENT_ID) REFERENCES TREATMENTS (ID),
    CONSTRAINT UK_TREATMENT_WORKS UNIQUE (TREATMENT_ID,TYPE_WORK));

CREATE TABLE TREATMENTS_WORKS_DETAILS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    WORKS_ID INT NOT NULL,
    TYPE_WD INT NOT NULL,
    CONSTRAINT FK_TWD_TYPES FOREIGN KEY (TYPE_WD) REFERENCES TYPES (ID),
    CONSTRAINT FK_TWD_WORKS FOREIGN KEY (WORKS_ID) REFERENCES TREATMENTS_WORKS (ID),
    CONSTRAINT UK_TWS UNIQUE (WORKS_ID,TYPE_WD));

CREATE TABLE PRODUCTS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(1000)  NOT NULL,
    DESCRIPTION VARCHAR(4000),
    QUANTITY FLOAT NOT NULL DEFAULT 1,
    UNIT INT NOT NULL,
    ORG_ID INT NOT NULL,
    CONSTRAINT FK_PRODUCTS_TYPES FOREIGN KEY (UNIT) REFERENCES TYPES (ID),
    CONSTRAINT FK_PRODUCTS_ORG FOREIGN KEY (ORG_ID) REFERENCES ORGANIZATIONS (ID));

CREATE TABLE TREATMENTS_PRODUCTS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TREATMENT_ID INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    QUANTITY FLOAT NOT NULL DEFAULT 1,
    CONSTRAINT FK_TP_TREATMENTS FOREIGN KEY (TREATMENT_ID) REFERENCES TREATMENTS (ID),
    CONSTRAINT FK_TP_PRODUCTS FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS (ID),
    CONSTRAINT UK_TP UNIQUE (TREATMENT_ID,PRODUCT_ID));

CREATE TABLE TREATMENT_PLAGUES (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TREATMENT_ID INT NOT NULL,
    TYPE_PLAGUE INT NOT NULL,
    CONTROLLED INT NOT NULL,
    CONSTRAINT FK_TPLAGUE_TREATMENTS FOREIGN KEY (TREATMENT_ID) REFERENCES TREATMENTS (ID),
    CONSTRAINT FK_TPLAGUE_TYPE FOREIGN KEY (TYPE_PLAGUE) REFERENCES TYPES (ID),
    CONSTRAINT FK_TPLAGUE_TYPE_CONTROL FOREIGN KEY (CONTROLLED) REFERENCES TYPES (ID),
    CONSTRAINT UK_TPLAGUE UNIQUE (TREATMENT_ID,TYPE_PLAGUE));

CREATE TABLE TREATMENT_SURVEY (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TREATMENT_ID INT NOT NULL,
    TYPE_SURVEY INT NOT NULL,
    SUBTYPE_SURVEY INT NOT NULL,
    CHECKED INT,
    CONSTRAINT FK_TSURVEY_TREATMENTS FOREIGN KEY (TREATMENT_ID) REFERENCES TREATMENTS (ID),
    CONSTRAINT FK_TSURVEY_TYPE FOREIGN KEY (TYPE_SURVEY) REFERENCES TYPES (ID),
    CONSTRAINT FK_TSURVEY_SUBTYPE FOREIGN KEY (SUBTYPE_SURVEY) REFERENCES TYPES (ID),
    CONSTRAINT UK_TSURVEY UNIQUE (TREATMENT_ID,TYPE_SURVEY,SUBTYPE_SURVEY));

CREATE TABLE ROLES_USERS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_ID INT NOT NULL,
    ROLE VARCHAR(20),
    CONSTRAINT UK_ROL_USER UNIQUE (USER_ID,ROLE),
    CONSTRAINT FK_ROL_USER_USERS FOREIGN KEY (USER_ID) REFERENCES USERS (ID));

insert into ORGANIZATIONS (ID,NAME)
values (1,'SAN JUSTO');

insert into TYPES (ID,TYPE,SHORT_NAME,DESCRIPTION,ORG_ID)
values (1,'CUSTOMER_TYPE','NORMAL','Cliente normal',1);
insert into TYPES (ID,TYPE,SHORT_NAME,DESCRIPTION,ORG_ID)
values (2,'CUSTOMER_TYPE','REGULAR','Cliente regular',1);
insert into TYPES (ID,TYPE,SHORT_NAME,DESCRIPTION,ORG_ID)
values (3,'CUSTOMER_TYPE','CRITICO','Cliente critico',1);

insert into TYPES (ID,TYPE,SHORT_NAME,DESCRIPTION,ORG_ID)
values (4,'JOB TYPE','DESINSECTACION','Desinsectación',1);
insert into TYPES (ID,TYPE,SHORT_NAME,DESCRIPTION,ORG_ID,PARENT_TYPE)
values (5,'JOB DETAIL TYPE','GEL','Gel',1,4);
insert into TYPES (ID,TYPE,SHORT_NAME,DESCRIPTION,ORG_ID,PARENT_TYPE)
values (6,'JOB DETAIL TYPE','LIQUIDO','Líquido',1,4);
insert into TYPES (ID,TYPE,SHORT_NAME,DESCRIPTION,ORG_ID,PARENT_TYPE)
values (7,'JOB DETAIL TYPE','HUMO','Humo',1,4);

insert into TYPES (ID,TYPE,SHORT_NAME,DESCRIPTION,ORG_ID)
values (8,'JOB TYPE','DESRATIZACION','Desratización',1);
insert into TYPES (ID,TYPE,SHORT_NAME,DESCRIPTION,ORG_ID,PARENT_TYPE)
values (9,'JOB DETAIL TYPE','CEBOS','Cebos',1,8);
insert into TYPES (ID,TYPE,SHORT_NAME,DESCRIPTION,ORG_ID,PARENT_TYPE)
values (10,'JOB DETAIL TYPE','PEGAMENTOSAS','Pegamentosas',1,8);
insert into TYPES (ID,TYPE,SHORT_NAME,DESCRIPTION,ORG_ID,PARENT_TYPE)
values (11,'JOB DETAIL TYPE','TRAMPA','Trampa',1,8);

insert into TYPES (ID,TYPE,SHORT_NAME,DESCRIPTION,ORG_ID)
values (12,'JOB TYPE','DESINFECCION','Desinfección',1);
insert into TYPES (ID,TYPE,SHORT_NAME,DESCRIPTION,ORG_ID,PARENT_TYPE)
values (13,'JOB DETAIL TYPE','ASPERCION','Asperción',1,12);

insert into TYPES (ID,TYPE,SHORT_NAME,DESCRIPTION,ORG_ID)
values (14,'MOTIVES','CERRADO','Cerrado',1);
insert into TYPES (ID,TYPE,SHORT_NAME,DESCRIPTION,ORG_ID)
values (15,'MOTIVES','POSTPUESTO','Cliente Pospuso',1);

insert into TYPES (ID,TYPE,SHORT_NAME,DESCRIPTION,ORG_ID)
values (16,'PLAGUES_CONTROLLED','SI','Si',1);
insert into TYPES (ID,TYPE,SHORT_NAME,DESCRIPTION,ORG_ID)
values (17,'PLAGUES_CONTROLLED','NO','No',1);
insert into TYPES (ID,TYPE,SHORT_NAME,DESCRIPTION,ORG_ID)
values (18,'PLAGUES_CONTROLLED','CRITICO','Crítico',1);

insert into TYPES (ID,TYPE,SHORT_NAME,DESCRIPTION,ORG_ID)
values (19,'PLAGUES','CUCARACHAS','Cucarachas',1);
insert into TYPES (ID,TYPE,SHORT_NAME,DESCRIPTION,ORG_ID)
values (20,'PLAGUES','HORMIGAS','Hormigas',1);

insert into TYPES (ID,TYPE,SHORT_NAME,DESCRIPTION,ORG_ID)
values (21,'SURVEY','REALIZAR CERRAMIENTOS','Realizar Cerramientos',1);
insert into TYPES (ID,TYPE,SHORT_NAME,DESCRIPTION,ORG_ID,PARENT_TYPE)
values (22,'SURVEY','VENTANA','Ventanas',1,21);
insert into TYPES (ID,TYPE,SHORT_NAME,DESCRIPTION,ORG_ID,PARENT_TYPE)
values (23,'SURVEY','BURLETES','Burletes',1,21);
insert into TYPES (ID,TYPE,SHORT_NAME,DESCRIPTION,ORG_ID,PARENT_TYPE)
values (24,'SURVEY','PORTONES','Portones',1,21);

insert into TYPES (ID,TYPE,SHORT_NAME,DESCRIPTION,ORG_ID)
values (25,'PRODUCT_UNIT','ml','mililitros',1);

insert into PRODUCTS (ID,NAME,UNIT,ORG_ID)
values (1,'FIPRONIL 2%',25,1);
insert into PRODUCTS (ID,NAME,UNIT,ORG_ID)
values (2,'CIPERMETRINA 2%',25,1);
insert into PRODUCTS (ID,NAME,UNIT,ORG_ID)
values (3,'PERMETRINA 2%',25,1);

insert into CUSTOMERS (ID,CUSTOMER_NAME,ADDRESS,NEIGHBORHOOD,CITY,PHONE,EMAIL,START_DATE,CUSTOMER_TYPE,ENABLED,ORG_ID)
values (1,'Pablo Vaca','Mza 221 Lote 12','La Estanzuela 2','LA CALERA','1533731837','vacapablo72@gmail.com',current_date(),1,1,1);

insert into BRANCHES (ID,BRANCH_NAME,ADDRESS,NEIGHBORHOOD,CITY,PHONE,CUSTOMER_ID,BRANCH_TYPE,ORG_ID)
values (1,'Branch 1','Mza 221 lote 12','La Estanzuela 2','La Calera','402775',1,1,1);
insert into BRANCHES (ID,BRANCH_NAME,ADDRESS,NEIGHBORHOOD,CITY,PHONE,CUSTOMER_ID,BRANCH_TYPE,ORG_ID)
values (2,'Branch 2','Mza 224 lote 121','La Estanzuela','La Calera','402779',1,1,1);

insert into CONTACTS (ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE,ORG_ID)
values (1,'Contacto','Uno','contacto1@email.com','12345678',1);
insert into CONTACTS (ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE,ORG_ID)
values (2,'Contacto','dos','contacto2@email.com','12345678',1);
insert into CONTACTS (ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE,ORG_ID)
values (3,'Contacto','tres','contacto3@email.com','12345678',1);
insert into CONTACTS (ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE,ORG_ID)
values (4,'Contacto','cuatro','contacto4@email.com','12345678',1);

insert into BRANCHES_CONTACTS (CONTACT_ID,BRANCH_ID)
values (1,1);
insert into BRANCHES_CONTACTS (CONTACT_ID,BRANCH_ID)
values (3,1);
insert into BRANCHES_CONTACTS (CONTACT_ID,BRANCH_ID)
values (2,1);
insert into BRANCHES_CONTACTS (CONTACT_ID,BRANCH_ID)
values (4,1);

insert into USERS (FIRST_NAME,LAST_NAME,EMAIL,ORG_ID,USERNAME,PASSWORD)
values ('Pablo','Vaca','vacapablo72@gmail.com',1,'pvaca','1000:4a7a2f5a02edb7b256dd9db4eec7ece1054a3e785d3276fbb4f46b4870837cd964c24a78:53e04ef6893f03a667fd18bc5a9b5fd460b1d4cbe01631e0b8296db12ab68454e48e6a85');

commit;